os:
  - osx
  - windows
language: node_js
node_js:
  - '8'
branchs:
  only:
    - master
script :
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm run build:win; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run build:mac-dmg; fi
deploy:
  provider: releases
  file:
    - "./package/fimage.dmg"
    - "./package/fimage-win32-ia32"
    - "./package/fimage-win32-x64"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
  api_key:
    secure: if/NUSKowWD8UpSB32Jdq2OvN7wf8Hb4wCMDEuWKkeS0d7c9hu4jfSz3cJ+TafiXQX1Z1j1K7YcFiRMHfGHjyLV7o8FK3l/O8waMt5ZOkEnSjCpAQS01+KlcSO+PIotee0yMUOZ2B4wxU0Km2mXzbev7kpwObeQPReTN9krPFAg0ELA4LL/8YiWEEYP217OQOgHw6GqlagDKFr4z4/9GDJ5LrgzMyDQ5Eh6WKU/TmMqwZ1X19wPsPjIGZAcEGo74N+rvqmS0Nr7jNrhuaUkREtUHa2CEGE9WOYKpWyLX/VXxBfx7GSnpfWta0wwfPOow92xB9ixJh6nPYH+YFUE7HclFjd5tYesFlO9FOoon2RGK4X4AImS8sH2oglphfZSK05+zxKWVE2Wjxoux0FuwdmjfCSeGsmegkI7kWcZ1aG2gOwsYWWfuepkGdzWcthQCSLEtGSlWbKrS6vrr9j7qyH4vOFbweOGu5Mb55n/dt6MHuS/4Vp0hD/P41zzrCzPuEBBfrmhKDLRTKYkwBuKBqRYTJfZRXOad4WQNO+flysQAE9Fgfg8LZ8H4DPoD0qBw3QSlzn9V9BtvBtgMNgKd22k0IZ7GgarloK/Ut/XfDy25I5UL6czW8j0/Tuvbws5bmC+JhQg0FzxOCIr5eV/U0+M/bcQEuKJm9nuey9Uwzkg=