os:
  - osx
language: node_js
node_js:
  - '10'
branchs:
  only:
    - master
script :
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run build:mac-dmg; fi
deploy:
  provider: releases
  file:
    - "./package/fimage.dmg"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true