platform:
  - x64
install:
  - npm install
build_script:
  - npm run package:win
environment:
  nodejs_version: '10'
artifacts:
  - path: packages\Fimage.exe
deploy:
  provider: GitHub
  auth_token:
    secure: Og2Iq8r0B401XDHsExtqkO78D4JaWWhWjSEilil5TvCD6KU3oruXB1wuAwad0ZzG
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
