platform:
  - x64
install:
  - npm install
build_script :
  - npm run build:win
environment:
  nodejs_version: "10"
artifacts :
    - path: package\fimage-win32-ia32
    - path: package\fimage-win32-x64
deploy:
  provider: GitHub
  auth_token:
    secure: Og2Iq8r0B401XDHsExtqkO78D4JaWWhWjSEilil5TvCD6KU3oruXB1wuAwad0ZzG
  on:
    branch: master
    APPVEYOR_REPO_TAG: true