platform:
  - x64
build_script :
  - npm run build:win
environment:
  nodejs_version: "10"
  token:
    secure: Og2Iq8r0B401XDHsExtqkO78D4JaWWhWjSEilil5TvCD6KU3oruXB1wuAwad0ZzG
deploy:
    provider: GitHub
    artifacts:
      - path: package
        name: fimage-win32-ia32 fimage-win32-x64
    on:
      branch: master
      APPVEYOR_REPO_TAG: true